POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Musti Koira",
    "number": "045-6783256"
}

###
POST https://lit-reaches-51232.herokuapp.com/api/persons/
Content-Type: application/json

{
    "name": "Musti Koira",
    "number": "045-6783256"
}